// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/jobs": {
            "post": {
                "tags": [
                    "Jobs"
                ],
                "parameters": [
                    {
                        "description": "CreateRequestDto",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/jobs_dto.CreateRequestDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/jobs_dto.CreateResponseDto"
                        }
                    }
                }
            }
        },
        "/jobs/all/pending": {
            "get": {
                "tags": [
                    "Jobs"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/jobs_dto.FetchResponseDto"
                            }
                        }
                    }
                }
            }
        },
        "/jobs/{jobID}": {
            "get": {
                "tags": [
                    "Jobs"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "jobID",
                        "name": "jobID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/jobs_dto.FetchResponseDto"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Jobs"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "jobID",
                        "name": "jobID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "jobs_dto.CreateRequestDto": {
            "type": "object",
            "required": [
                "apiUrl",
                "executedAt",
                "jobName"
            ],
            "properties": {
                "apiUrl": {
                    "type": "string"
                },
                "executedAt": {
                    "type": "string"
                },
                "jobName": {
                    "type": "string"
                }
            }
        },
        "jobs_dto.CreateResponseDto": {
            "type": "object",
            "properties": {
                "apiUrl": {
                    "type": "string"
                },
                "createdTime": {
                    "type": "string"
                },
                "executedAt": {
                    "type": "string"
                },
                "jobName": {
                    "type": "string"
                }
            }
        },
        "jobs_dto.FetchResponseDto": {
            "type": "object",
            "properties": {
                "apiUrl": {
                    "type": "string"
                },
                "createdTime": {
                    "type": "string"
                },
                "executedAt": {
                    "type": "string"
                },
                "jobID": {
                    "type": "integer"
                },
                "jobName": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Job Scheduler API",
	Description:      "This is a job scheduler API for scheduling jobs and running them at a specified time",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
