basePath: /api/v1
definitions:
  jobs_dto.CreateRequestDto:
    properties:
      apiUrl:
        type: string
      executedAt:
        type: string
      jobName:
        type: string
    required:
    - apiUrl
    - executedAt
    - jobName
    type: object
  jobs_dto.CreateResponseDto:
    properties:
      apiUrl:
        type: string
      createdTime:
        type: string
      executedAt:
        type: string
      jobName:
        type: string
    type: object
  jobs_dto.FetchResponseDto:
    properties:
      apiUrl:
        type: string
      createdTime:
        type: string
      executedAt:
        type: string
      jobID:
        type: integer
      jobName:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a job scheduler API for scheduling jobs and running them at
    a specified time
  title: Job Scheduler API
  version: "1.0"
paths:
  /jobs:
    post:
      parameters:
      - description: CreateRequestDto
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/jobs_dto.CreateRequestDto'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/jobs_dto.CreateResponseDto'
      tags:
      - Jobs
  /jobs/{jobID}:
    delete:
      parameters:
      - description: jobID
        in: path
        name: jobID
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - Jobs
    get:
      parameters:
      - description: jobID
        in: path
        name: jobID
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/jobs_dto.FetchResponseDto'
      tags:
      - Jobs
  /jobs/all/pending:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/jobs_dto.FetchResponseDto'
            type: array
      tags:
      - Jobs
swagger: "2.0"
